ning test function
            result = fun(unitTest)
            # Unexpected errors
            error 